# Generated by Django 5.0.2 on 2024-03-09 16:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BusInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bus_no', models.CharField(max_length=10)),
                ('bus_name', models.CharField(max_length=50)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Travelinfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_place', models.CharField(max_length=100)),
                ('destination', models.CharField(max_length=100)),
                ('km', models.IntegerField()),
                ('reverse', models.BooleanField(blank=True, default=False)),
                ('bus_no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ticket.businfo')),
            ],
        ),
        migrations.CreateModel(
            name='Stop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('km', models.IntegerField()),
                ('stopname', models.CharField(max_length=100)),
                ('bus_no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ticket.travelinfo')),
            ],
        ),
    ]
