# Generated by Django 5.0.2 on 2024-03-26 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='travelinfo',
            name='min_price',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
